add colors

diff --git a/appveyor.yml b/appveyor.yml
--- a/appveyor.yml
+++ b/appveyor.yml
@@ -2,7 +2,26 @@ init:
 - appveyor version
 - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
 - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
-
+- sh: |
+    # Only use colors if connected to a terminal
+    if [ -t 1 ]; then
+      RED=$(printf '\033[31m')
+      GREEN=$(printf '\033[32m')
+      YELLOW=$(printf '\033[33m')
+      BLUE=$(printf '\033[34m')
+      BOLD=$(printf '\033[1m')
+      RESET=$(printf '\033[m')
+      NC=$(printf '\033[m')
+    else
+      RED=""
+      GREEN=""
+      YELLOW=""
+      BLUE=""
+      BOLD=""
+      RESET=""
+      NC=""
+    fi
+    
 test_script:
 - sh: |
     declare JDK_VERSIONS=( "7" "8" "9" "10" "11" "12" "13" "14" )
@@ -22,9 +41,9 @@ test_script:
         java -version
         javac -version
         if [[ $(java -version 2>&1) =~ ${VERSIONS[$v]} ]] && [[ $(javac -version 2>&1) =~ ${VERSIONS[$v]} ]]; then
-            echo "Version is Correct"
+            echo "${GREEN}Version is Correct${NC}"
         else
-            echo "[ERROR] Version of JDK is incorrect!" 1>&2;
+            echo "${RED}[ERROR] Version of JDK is incorrect!${NC}" 1>&2;
             return 2;
         fi
     done
